/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    ExampleAIMState: {
      address: "0x959922bE3CAee4b8Cd9a407cc3ac1C251C2007B1",
      abi: [
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_constitutionHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "_initialModel",
              type: "string",
            },
            {
              internalType: "address",
              name: "_admin",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "ECDSAInvalidSignature",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "length",
              type: "uint256",
            },
          ],
          name: "ECDSAInvalidSignatureLength",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "s",
              type: "bytes32",
            },
          ],
          name: "ECDSAInvalidSignatureS",
          type: "error",
        },
        {
          inputs: [],
          name: "ReentrancyGuardReentrantCall",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "citizen",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "totalCitizens",
              type: "uint256",
            },
          ],
          name: "CitizenJoined",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "bytes32",
              name: "newHash",
              type: "bytes32",
            },
          ],
          name: "ConstitutionUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "string",
              name: "newModel",
              type: "string",
            },
          ],
          name: "ModelUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "proposalId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "decision",
              type: "string",
            },
            {
              indexed: true,
              internalType: "address",
              name: "teeAddress",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "aiResponseHash",
              type: "bytes32",
            },
          ],
          name: "ProposalDecided",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "proposalId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "ProposalExecuted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "proposalId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "citizen",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "hasAction",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "proposalHash",
              type: "bytes32",
            },
          ],
          name: "ProposalSubmitted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "signer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "model",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "expiresAt",
              type: "uint256",
            },
          ],
          name: "TEERegistered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "signer",
              type: "address",
            },
          ],
          name: "TEERevoked",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "TreasuryDeposit",
          type: "event",
        },
        {
          inputs: [],
          name: "MAX_TREASURY_REQUEST_BPS",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "admin",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "attestationTTL",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "citizenCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "citizenList",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "constitutionHash",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "currentModel",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "proposalId",
              type: "uint256",
            },
          ],
          name: "executeProposal",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "proposalId",
              type: "uint256",
            },
          ],
          name: "getProposal",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "citizen",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "proposalText",
                  type: "string",
                },
                {
                  internalType: "bool",
                  name: "hasAction",
                  type: "bool",
                },
                {
                  internalType: "address",
                  name: "actionTarget",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "actionValue",
                  type: "uint256",
                },
                {
                  internalType: "bytes32",
                  name: "constitutionHash",
                  type: "bytes32",
                },
                {
                  internalType: "enum ExampleAIMState.ProposalStatus",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "string",
                  name: "aiDecision",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "aiReasoning",
                  type: "string",
                },
                {
                  internalType: "bytes32",
                  name: "aiResponseHash",
                  type: "bytes32",
                },
                {
                  internalType: "bytes32",
                  name: "requestHash",
                  type: "bytes32",
                },
                {
                  internalType: "address",
                  name: "teeAddress",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "decidedAt",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "executed",
                  type: "bool",
                },
              ],
              internalType: "struct ExampleAIMState.Proposal",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "proposalId",
              type: "uint256",
            },
          ],
          name: "getProposalHash",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "isCitizen",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "signer",
              type: "address",
            },
          ],
          name: "isTEETrusted",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "join",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "lastProposalTime",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "proposalCooldown",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "proposalCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "proposals",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "citizen",
              type: "address",
            },
            {
              internalType: "string",
              name: "proposalText",
              type: "string",
            },
            {
              internalType: "bool",
              name: "hasAction",
              type: "bool",
            },
            {
              internalType: "address",
              name: "actionTarget",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "actionValue",
              type: "uint256",
            },
            {
              internalType: "bytes32",
              name: "constitutionHash",
              type: "bytes32",
            },
            {
              internalType: "enum ExampleAIMState.ProposalStatus",
              name: "status",
              type: "uint8",
            },
            {
              internalType: "string",
              name: "aiDecision",
              type: "string",
            },
            {
              internalType: "string",
              name: "aiReasoning",
              type: "string",
            },
            {
              internalType: "bytes32",
              name: "aiResponseHash",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "requestHash",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "teeAddress",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "decidedAt",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "executed",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "signer",
              type: "address",
            },
            {
              internalType: "string",
              name: "model",
              type: "string",
            },
          ],
          name: "registerTEESigner",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "signer",
              type: "address",
            },
          ],
          name: "revokeTEESigner",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newAdmin",
              type: "address",
            },
          ],
          name: "setAdmin",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "ttl",
              type: "uint256",
            },
          ],
          name: "setAttestationTTL",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "cooldown",
              type: "uint256",
            },
          ],
          name: "setProposalCooldown",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "proposalId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "decision",
              type: "string",
            },
            {
              internalType: "string",
              name: "reasoning",
              type: "string",
            },
            {
              internalType: "bytes32",
              name: "aiResponseHashHex",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "requestHashHex",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "teeSignedText",
              type: "string",
            },
            {
              internalType: "bytes",
              name: "teeSignature",
              type: "bytes",
            },
          ],
          name: "submitAIDecision",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "proposalText",
              type: "string",
            },
            {
              internalType: "bool",
              name: "hasAction",
              type: "bool",
            },
            {
              internalType: "address",
              name: "actionTarget",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "actionValue",
              type: "uint256",
            },
          ],
          name: "submitProposal",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "treasuryBalance",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "trustedSigners",
          outputs: [
            {
              internalType: "bool",
              name: "trusted",
              type: "bool",
            },
            {
              internalType: "string",
              name: "model",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "attestedAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "expiresAt",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "newHash",
              type: "bytes32",
            },
          ],
          name: "updateConstitution",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "newModel",
              type: "string",
            },
          ],
          name: "updateModel",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 22,
    },
  },
  11155111: {
    AvocadoNation: {
      address: "0x2d4E903d56304Df0b93D3b919b8f610E17fC3E78",
      abi: [
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_constitutionHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "_initialModel",
              type: "string",
            },
            {
              internalType: "address",
              name: "_admin",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "ECDSAInvalidSignature",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "length",
              type: "uint256",
            },
          ],
          name: "ECDSAInvalidSignatureLength",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "s",
              type: "bytes32",
            },
          ],
          name: "ECDSAInvalidSignatureS",
          type: "error",
        },
        {
          inputs: [],
          name: "ReentrancyGuardReentrantCall",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "citizen",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "totalCitizens",
              type: "uint256",
            },
          ],
          name: "CitizenDenounced",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "citizen",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "totalCitizens",
              type: "uint256",
            },
          ],
          name: "CitizenJoined",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "bytes32",
              name: "newHash",
              type: "bytes32",
            },
          ],
          name: "ConstitutionUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "string",
              name: "newModel",
              type: "string",
            },
          ],
          name: "ModelUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "proposalId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "decision",
              type: "string",
            },
            {
              indexed: true,
              internalType: "address",
              name: "teeAddress",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "aiResponseHash",
              type: "bytes32",
            },
          ],
          name: "ProposalDecided",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "proposalId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "ProposalExecuted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "proposalId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "citizen",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "hasAction",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "proposalHash",
              type: "bytes32",
            },
          ],
          name: "ProposalSubmitted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "signer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "model",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "expiresAt",
              type: "uint256",
            },
          ],
          name: "TEERegistered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "signer",
              type: "address",
            },
          ],
          name: "TEERevoked",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "TreasuryDeposit",
          type: "event",
        },
        {
          inputs: [],
          name: "JOIN_FEE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MAX_TREASURY_REQUEST_BPS",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "admin",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "attestationTTL",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "citizenCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "citizenList",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "constitutionHash",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "currentModel",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "denounce",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "donate",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "proposalId",
              type: "uint256",
            },
          ],
          name: "executeProposal",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "proposalId",
              type: "uint256",
            },
          ],
          name: "getProposal",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "citizen",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "proposalText",
                  type: "string",
                },
                {
                  internalType: "bool",
                  name: "hasAction",
                  type: "bool",
                },
                {
                  internalType: "address",
                  name: "actionTarget",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "actionValue",
                  type: "uint256",
                },
                {
                  internalType: "bytes32",
                  name: "constitutionHash",
                  type: "bytes32",
                },
                {
                  internalType: "enum AvocadoNation.ProposalStatus",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "string",
                  name: "aiDecision",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "aiReasoning",
                  type: "string",
                },
                {
                  internalType: "bytes32",
                  name: "aiResponseHash",
                  type: "bytes32",
                },
                {
                  internalType: "bytes32",
                  name: "requestHash",
                  type: "bytes32",
                },
                {
                  internalType: "address",
                  name: "teeAddress",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "decidedAt",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "executed",
                  type: "bool",
                },
              ],
              internalType: "struct AvocadoNation.Proposal",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "proposalId",
              type: "uint256",
            },
          ],
          name: "getProposalHash",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "isCitizen",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "signer",
              type: "address",
            },
          ],
          name: "isTEETrusted",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "join",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "lastProposalTime",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "proposalCooldown",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "proposalCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "proposals",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "citizen",
              type: "address",
            },
            {
              internalType: "string",
              name: "proposalText",
              type: "string",
            },
            {
              internalType: "bool",
              name: "hasAction",
              type: "bool",
            },
            {
              internalType: "address",
              name: "actionTarget",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "actionValue",
              type: "uint256",
            },
            {
              internalType: "bytes32",
              name: "constitutionHash",
              type: "bytes32",
            },
            {
              internalType: "enum AvocadoNation.ProposalStatus",
              name: "status",
              type: "uint8",
            },
            {
              internalType: "string",
              name: "aiDecision",
              type: "string",
            },
            {
              internalType: "string",
              name: "aiReasoning",
              type: "string",
            },
            {
              internalType: "bytes32",
              name: "aiResponseHash",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "requestHash",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "teeAddress",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "decidedAt",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "executed",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "signer",
              type: "address",
            },
            {
              internalType: "string",
              name: "model",
              type: "string",
            },
          ],
          name: "registerTEESigner",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "signer",
              type: "address",
            },
          ],
          name: "revokeTEESigner",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newAdmin",
              type: "address",
            },
          ],
          name: "setAdmin",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "ttl",
              type: "uint256",
            },
          ],
          name: "setAttestationTTL",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "cooldown",
              type: "uint256",
            },
          ],
          name: "setProposalCooldown",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "proposalId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "decision",
              type: "string",
            },
            {
              internalType: "string",
              name: "reasoning",
              type: "string",
            },
            {
              internalType: "bytes32",
              name: "aiResponseHashHex",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "requestHashHex",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "teeSignedText",
              type: "string",
            },
            {
              internalType: "bytes",
              name: "teeSignature",
              type: "bytes",
            },
          ],
          name: "submitAIDecision",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "proposalText",
              type: "string",
            },
            {
              internalType: "bool",
              name: "hasAction",
              type: "bool",
            },
            {
              internalType: "address",
              name: "actionTarget",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "actionValue",
              type: "uint256",
            },
          ],
          name: "submitProposal",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "treasuryBalance",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "trustedSigners",
          outputs: [
            {
              internalType: "bool",
              name: "trusted",
              type: "bool",
            },
            {
              internalType: "string",
              name: "model",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "attestedAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "expiresAt",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "newHash",
              type: "bytes32",
            },
          ],
          name: "updateConstitution",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "newModel",
              type: "string",
            },
          ],
          name: "updateModel",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 10472276,
    },
    ExampleAIMState: {
      address: "0x5B68e5CE9c55E3b0688dCD045d48F0ab58F3AD2B",
      abi: [
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_constitutionHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "_initialModel",
              type: "string",
            },
            {
              internalType: "address",
              name: "_admin",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "ECDSAInvalidSignature",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "length",
              type: "uint256",
            },
          ],
          name: "ECDSAInvalidSignatureLength",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "s",
              type: "bytes32",
            },
          ],
          name: "ECDSAInvalidSignatureS",
          type: "error",
        },
        {
          inputs: [],
          name: "ReentrancyGuardReentrantCall",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "citizen",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "totalCitizens",
              type: "uint256",
            },
          ],
          name: "CitizenDenounced",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "citizen",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "totalCitizens",
              type: "uint256",
            },
          ],
          name: "CitizenJoined",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "bytes32",
              name: "newHash",
              type: "bytes32",
            },
          ],
          name: "ConstitutionUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "string",
              name: "newModel",
              type: "string",
            },
          ],
          name: "ModelUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "proposalId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "decision",
              type: "string",
            },
            {
              indexed: true,
              internalType: "address",
              name: "teeAddress",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "aiResponseHash",
              type: "bytes32",
            },
          ],
          name: "ProposalDecided",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "proposalId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "ProposalExecuted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "proposalId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "citizen",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "hasAction",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "proposalHash",
              type: "bytes32",
            },
          ],
          name: "ProposalSubmitted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "signer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "model",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "expiresAt",
              type: "uint256",
            },
          ],
          name: "TEERegistered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "signer",
              type: "address",
            },
          ],
          name: "TEERevoked",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "TreasuryDeposit",
          type: "event",
        },
        {
          inputs: [],
          name: "JOIN_FEE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MAX_TREASURY_REQUEST_BPS",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "admin",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "attestationTTL",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "citizenCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "citizenList",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "constitutionHash",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "currentModel",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "denounce",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "donate",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "proposalId",
              type: "uint256",
            },
          ],
          name: "executeProposal",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "proposalId",
              type: "uint256",
            },
          ],
          name: "getProposal",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "citizen",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "proposalText",
                  type: "string",
                },
                {
                  internalType: "bool",
                  name: "hasAction",
                  type: "bool",
                },
                {
                  internalType: "address",
                  name: "actionTarget",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "actionValue",
                  type: "uint256",
                },
                {
                  internalType: "bytes32",
                  name: "constitutionHash",
                  type: "bytes32",
                },
                {
                  internalType: "enum ExampleAIMState.ProposalStatus",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "string",
                  name: "aiDecision",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "aiReasoning",
                  type: "string",
                },
                {
                  internalType: "bytes32",
                  name: "aiResponseHash",
                  type: "bytes32",
                },
                {
                  internalType: "bytes32",
                  name: "requestHash",
                  type: "bytes32",
                },
                {
                  internalType: "address",
                  name: "teeAddress",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "decidedAt",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "executed",
                  type: "bool",
                },
              ],
              internalType: "struct ExampleAIMState.Proposal",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "proposalId",
              type: "uint256",
            },
          ],
          name: "getProposalHash",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "isCitizen",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "signer",
              type: "address",
            },
          ],
          name: "isTEETrusted",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "join",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "lastProposalTime",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "proposalCooldown",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "proposalCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "proposals",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "citizen",
              type: "address",
            },
            {
              internalType: "string",
              name: "proposalText",
              type: "string",
            },
            {
              internalType: "bool",
              name: "hasAction",
              type: "bool",
            },
            {
              internalType: "address",
              name: "actionTarget",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "actionValue",
              type: "uint256",
            },
            {
              internalType: "bytes32",
              name: "constitutionHash",
              type: "bytes32",
            },
            {
              internalType: "enum ExampleAIMState.ProposalStatus",
              name: "status",
              type: "uint8",
            },
            {
              internalType: "string",
              name: "aiDecision",
              type: "string",
            },
            {
              internalType: "string",
              name: "aiReasoning",
              type: "string",
            },
            {
              internalType: "bytes32",
              name: "aiResponseHash",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "requestHash",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "teeAddress",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "decidedAt",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "executed",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "signer",
              type: "address",
            },
            {
              internalType: "string",
              name: "model",
              type: "string",
            },
          ],
          name: "registerTEESigner",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "signer",
              type: "address",
            },
          ],
          name: "revokeTEESigner",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newAdmin",
              type: "address",
            },
          ],
          name: "setAdmin",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "ttl",
              type: "uint256",
            },
          ],
          name: "setAttestationTTL",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "cooldown",
              type: "uint256",
            },
          ],
          name: "setProposalCooldown",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "proposalId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "decision",
              type: "string",
            },
            {
              internalType: "string",
              name: "reasoning",
              type: "string",
            },
            {
              internalType: "bytes32",
              name: "aiResponseHashHex",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "requestHashHex",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "teeSignedText",
              type: "string",
            },
            {
              internalType: "bytes",
              name: "teeSignature",
              type: "bytes",
            },
          ],
          name: "submitAIDecision",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "proposalText",
              type: "string",
            },
            {
              internalType: "bool",
              name: "hasAction",
              type: "bool",
            },
            {
              internalType: "address",
              name: "actionTarget",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "actionValue",
              type: "uint256",
            },
          ],
          name: "submitProposal",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "treasuryBalance",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "trustedSigners",
          outputs: [
            {
              internalType: "bool",
              name: "trusted",
              type: "bool",
            },
            {
              internalType: "string",
              name: "model",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "attestedAt",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "expiresAt",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "newHash",
              type: "bytes32",
            },
          ],
          name: "updateConstitution",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "newModel",
              type: "string",
            },
          ],
          name: "updateModel",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 10471990,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
